name: Checks

on:
  pull_request:
  push:
    paths-ignore:
      - "assets/**"
      - ".vscode/**"
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install
        with:
          transcrypt_password: ${{ secrets.transcrypt_password }}

      - name: Check
        run: yarn check

      - name: Lint
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install
        with:
          transcrypt_password: ${{ secrets.transcrypt_password }}

      - name: Install playwright
        run: npx playwright install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel Project
        run: cd code/tamagui.dev && vercel link --project site --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: cd code/tamagui.dev && vercel env pull .env --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          command: "yarn test:ci"
